### ISSUE TITLE
id & specificity

### ISSUE THREAD

**Issue by rikschennink** [DaveBitter/minor-webdev_css-to-the-rescue#10]
Ik snap het gebruik er van ivm targetting, maar ik zou het niet gebruiken om stijlen aan te koppelen ivm specificity (https://specificity.keegan.st). Probeer ook niet te specifiek te stylen (door nesting in preprocessor kan het zijn dat het niet op valt). 
`section#chat ol > li > p` kan ook zo `#chat p`.

**Comment by DaveBitter** [comment]
Good point, my thought process behind it was to not have these styles applied to p elements that might get added to the #chat section that are not chat messages. Perhaps it's better to change the selector to this and style those p elements when they are added. I'm changing it!
