### ISSUE TITLE
.btn--primary

### ISSUE THREAD

**Issue by rikschennink** [DaveBitter/minor-webdev_css-to-the-rescue#11]
Deze gewoon [type=submit] maken. In de praktijk ga je waarschijnlijk toch iets van een class nodig hebben maar voor deze opdracht is het denk ik passender om het attribute te gebruiken.

**Comment by DaveBitter** [comment]
I understand the logic behind the selector. Not using it was purely for the re-use of the buttons styles throughout the style-sheet. I will definitely use this in the case of wanting a separate style for submit buttons.
