### ISSUE TITLE
Picture with caption

### ISSUE THREAD

**Issue by vasilisvg** [DaveBitter/minor-webdev_css-to-the-rescue#14]
Dit probleem is complexer: Het plaatje moet _altijd_ helemaal zichtbaar zijn in elke viewport. Dus maximaal `100vh`, en maximaal `100vw`. Bovendien moet je ook altijd kunnen zien dat er een onderschrift is. En dit moet werken met een landscape en een portrait plaatje …
En kan je je nog herinneren hoeveel `em` breed een paragraaf maximaal mag zijn?
En hier is er iets mis met de aangeleverde HTML. Hier moet je dus wel iets aanpassen (-:

**Comment by DaveBitter** [comment]
De paragraaf heeft een max-width van 30em, dat is de bedoeling toch?

**Comment by vasilisvg** [comment]
Copypaste-foutje. Die regel had ik weg moeten halen. 30em is inderdaad prima.

**Comment by DaveBitter** [comment]
Ah oke! :) Heb het probleem met een modal opgelost die verschijnt bij het klikken op het plaatje
