### ISSUE TITLE
Step indicator

### ISSUE THREAD

**Issue by vasilisvg** [DaveBitter/minor-webdev_css-to-the-rescue#16]
Deze lijkt me nog niet af, toch?

**Comment by DaveBitter** [comment]
Wat zou hier nog aan toegevoegd moeten worden? De aangeleverde elementen zijn allemaal gestyled. 

![image](https://cloud.githubusercontent.com/assets/14149640/23277341/c4adb3b2-fa0d-11e6-8472-2bc193a1cf0e.png)

**Comment by vasilisvg** [comment]
Ah! Zo ziet het er op mijn browser uit! (Firefox op OSX). Maar jouw versie ziet er inderdaad prima uit. Ben wel benieuwd waarom het niet werkt op Firefox.

![](https://ndoe.nl/screen/screenshot-1487883335.png)

**Comment by DaveBitter** [comment]
Moet je browser geupdateted worden? Support van v53 

http://caniuse.com/#search=clip-path
