### ISSUE TITLE
Al met al

### ISSUE THREAD

**Issue by vasilisvg** [DaveBitter/minor-webdev_css-to-the-rescue#17]
Het ziet er op punten echt erg mooi uit!
Kijk eens of je hier een *echte* site van kan maken. Lukt het je om alle elementen op een logische manier te tonen? Het mag op één pagina, maar ook op meerdere pagina's. Het onderwerp mag je natuurlijk zelf weten.

**Comment by DaveBitter** [comment]
Thanks! :)
