### ISSUE TITLE
Media Item

### ISSUE THREAD

**Issue by rikschennink** [DaveBitter/minor-webdev_css-to-the-rescue#6]
Een lijst met media items is nog prettiger te navigeren als heel het item klikbaar is. Kan zonder de HTML aan te passen...

**Comment by DaveBitter** [comment]
Sure, I could give the h1 a height of 100%, but this will break styling. Is this what you mean?

**Comment by rikschennink** [comment]
Je kan met een ::after op de anchor een element maken wat het hele item bestrijkt.

**Comment by vasilisvg** [comment]
- Je hebt nu maar een visuele variant gemaakt van het media-element. Maar er zijn flink wat verschillende manieren te bedenken waarop je dit kunt laten zien. Zie bijvoorbeeld de homepage van [The Guardian](https://www.theguardian.com/international) of de linkerkolom van [de Volkskrant](http://www.volkskrant.nl). Kijk eens of je net zo'n lijst kan maken waarbij de eerste er anders uit ziet dan de rest.

**Comment by DaveBitter** [comment]
Alle punten verwerkt! :)
