### ISSUE TITLE
wildcard border-box

### ISSUE THREAD

**Issue by rikschennink** [DaveBitter/minor-webdev_css-to-the-rescue#9]
Ik ben hier nooit zo van (als iemand die plugins aanbied online) omdat hierdoor alle elementen ander layout gedrag gaan vertonen. Als je dus plugins gebruikt dan kan het zijn dat die breken omdat ze er van uit gaan dat elementen standaard op content-box staan.

**Comment by DaveBitter** [comment]
Excellent point! It turned out that i only really needed it on 5 elements.
